# Generated by Django 5.2.3 on 2025-08-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='defectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_id', models.CharField(max_length=100)),
                ('defect_name', models.CharField(max_length=250)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('assigned_by', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('defect_status', models.CharField(max_length=100)),
            ],
        ),
    ]
