# Generated by Django 5.2.3 on 2025-08-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='defectData',
        ),
    ]
