# Generated by Django 5.2.3 on 2025-08-04 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defects', '0002_delete_defectdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
                ('dev_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TesterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300)),
                ('experience', models.PositiveIntegerField()),
                ('is_admin', models.BooleanField(default=False)),
                ('tester_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='defectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_id', models.CharField(max_length=100)),
                ('defect_name', models.CharField(max_length=250)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('priority', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('defect_status', models.CharField(max_length=100)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.developerdata')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.testerdata')),
            ],
        ),
    ]
